### ISSUE TITLE
Recent release

### ISSUE THREAD

**Issue by collectVood** [Cog-Creators/Lavalink-Jars#1]
Hey there, I am curious what was changed in the latest release?

**Comment by aikaterna** [comment]
Devoxin's Soundcloud fix was included, Nin's stats fix/PR is still included, and the Lavalink.jar can still be run on Java 8, unlike the current Lavalink CI jars. This also uses Lavaplayer 1.3.22-pbj3. None of the experimental ip rotation is in this build.

So, in short, Soundcloud was fixed and Lavaplayer was bumped to one of the more stable and non experimental 1.3.22 releases.

**Comment by collectVood** [comment]
Thanks alot for the quick and detailed response!
