### ISSUE TITLE
Timescale?

### ISSUE THREAD

**Issue by Vretu-Dev** [Cog-Creators/Lavalink-Jars#12]
I don't know exactly what the error concerns, but it occurs when using filters in music
![Screenshot_2022-05-29-16-28-32-88_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/82831707/170874770-123e4650-315a-4e41-a477-598fc415e72e.jpg)

**Comment by aikaterna** [comment]
I'll have another release later that addresses this, but just for the record, what OS is this running on?

**Comment by Vretu-Dev** [comment]
> I'll have another release later that addresses this, but just for the record, what OS is this running on?

Linux aarch64

**Comment by aikaterna** [comment]
I mean more specifically, like Ubuntu 18 or Raspbian 64 bit.

**Comment by Vretu-Dev** [comment]
> I mean more specifically, like Ubuntu 18 or Raspbian 64 bit.

Canonical Ubuntu 20.04

**Comment by aikaterna** [comment]
Can you please try timescale transforms on <https://github.com/Cog-Creators/Lavalink-Jars/releases/tag/3.4.0_1347> and reply here whether it works or not? Alternatively you can find me in the JDA server if you wish to DM me. My discord tag is aikaterna and you will see recent messages from me in the lavalink and lavaplayer channels.

**Comment by Vretu-Dev** [comment]
> Can you please try timescale transforms on https://github.com/Cog-Creators/Lavalink-Jars/releases/tag/3.4.0_1347 and reply here whether it works or not? Alternatively you can find me in the JDA server if you wish to DM me. My discord tag is aikaterna and you will see recent messages from me in the lavalink and lavaplayer channels.

Yes its working

**Comment by aikaterna** [comment]
Thanks, I appreciate the help on this. If you have other issues in the future don't hesitate to open an issue with your logs.

**Comment by Vretu-Dev** [comment]
> Thanks, I appreciate the help on this. If you have other issues in the future don't hesitate to open an issue with your logs.

Sure thanks for the quick reply. ;)
