### ISSUE TITLE
Track skip

### ISSUE THREAD

**Issue by tlfn** [Cog-Creators/Lavalink-Jars#2]
Sometimes tracks that are based on Youtube Live Streaming or Soundcloud or Bandcamp skips without command

There are no error shows and just destroyed

**Comment by aikaterna** [comment]
I would need error logs to diagnose this further, but Youtube livestreams have always been problematic, and Soundcloud songs are not working on the latest published jar (build 846). We will be releasing a new jar soon that bumps Lavaplayer's and Lavalink's version that will resolve issues with Soundcloud tracks, but we have to wait on commits to Lavaplayer to be able to play YT mix urls, YT livestreaming, or other various urls that have issues via YT.

See related issues at:
https://github.com/sedmelluq/lavaplayer/issues/256
https://github.com/sedmelluq/lavaplayer/issues/259
