### ISSUE TITLE
Cannot load playlist

### ISSUE THREAD

**Issue by tlfn** [Cog-Creators/Lavalink-Jars#3]
It can load a playlist that includes a little like https://www.youtube.com/playlist?list=PL4C2OaC1jQqR3ICDBf4j1dH1Fk4uIo-Lx this URL.

But it cannot load a playlist that includes many things like https://www.youtube.com/playlist?list=PLzkuLC6Yvumv_Rd5apfPRWEcjf9b1JRnq

https://pastebin.com/raw/18eFR5hA this is an error log

**Comment by aikaterna** [comment]
Please see <https://github.com/sedmelluq/lavaplayer/issues/259> as NoCopyrightSounds is one of the urls that causes this error. When this issue is resolved in Lavaplayer we will include it in a new release here.
