### ISSUE TITLE
New update (v. 3.3.1.1)

### ISSUE THREAD

**Issue by 099Martin** [Cog-Creators/Lavalink-Jars#4]
Hello.
It would be very nice if someone could find the time to update this Lavalink version to a newer version (Lavalink's v. 3.3.1.1).
Another option would be providing some instructions on how to compile ourselves.

Thanks in advance.

**Comment by Drapersniper** [comment]
When there is an update upstream there will be updated in due time. This Jar if for use With Red-DiscordBot. If you want to use the latest version when it is released I would suggest you use Fred's version.

**Comment by aikaterna** [comment]
We use our own versioning here. Our current release is not only up to date with the Lavalink release that you refer to, but we have also included other PRs or code that is not published in Lavaplayer or Lavalink official releases, fixing some of the issues present and in some cases, PRing back to the main project. In other words... we've already completed your request.
