### ISSUE TITLE
Filters is not working!

### ISSUE THREAD

**Issue by Asherlam** [Cog-Creators/Lavalink-Jars#8]
```2021-08-31 04:48:43.819  INFO 27 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op": "filters", "guildId": "667016765137485846", "timescale": {"speed": 2.0, "pitch": 1.0, "rate": 1.0}} 2021-08-31 04:48:43.819  WARN 27 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : Unexpected operation: filters```

**Comment by aikaterna** [comment]
This build does not support filters. Please refer to the discussion on https://github.com/Cog-Creators/Lavalink-Jars/issues/5 - we will have filters when we are ready and not before.
